In [2]:
import pandas as pd

from mentoring.question_mentoring2 import contingency_table

In [3]:
data = pd.read_csv('Car_Insurance_Claim.csv')

In [5]:
data.head().T

,0,1,2,3,4
ID,569520,750365,199901,478866,731664
AGE,65+,16-25,16-25,16-25,26-39
GENDER,female,male,female,male,male
RACE,majority,majority,majority,majority,majority
DRIVING_EXPERIENCE,0-9y,0-9y,0-9y,0-9y,10-19y
EDUCATION,high school,none,high school,university,none
INCOME,upper class,poverty,working class,working class,working class
CREDIT_SCORE,0.629027,0.357757,0.493146,0.206013,0.388366
VEHICLE_OWNERSHIP,1.0,0.0,1.0,1.0,1.0
VEHICLE_YEAR,after 2015,before 2015,before 2015,before 2015,before 2015
MARRIED,0.0,0.0,0.0,0.0,0.0
CHILDREN,1.0,0.0,0.0,1.0,0.0
POSTAL_CODE,10238,10238,10238,32765,32765
ANNUAL_MILEAGE,12000.0,16000.0,11000.0,11000.0,12000.0
VEHICLE_TYPE,sedan,sedan,sedan,sedan,sedan
SPEEDING_VIOLATIONS,0,0,0,0,2
DUIS,0,0,0,0,0
PAST_ACCIDENTS,0,0,0,0,1
OUTCOME,0.0,1.0,0.0,0.0,1.0

In [6]:
data['CREDIT_SCORE'].describe()

count    9018.000000
mean        0.515813
std         0.137688
min         0.053358
25%         0.417191
50%         0.525033
75%         0.618312
max         0.960819
Name: CREDIT_SCORE, dtype: float64

In [7]:
data['DEFAULT'] = data['CREDIT_SCORE'].apply(lambda x: 1 if x > 0.5 else 0)

In [8]:
data.head()

,ID,AGE,GENDER,RACE,DRIVING_EXPERIENCE,EDUCATION,INCOME,CREDIT_SCORE,VEHICLE_OWNERSHIP,VEHICLE_YEAR,MARRIED,CHILDREN,POSTAL_CODE,ANNUAL_MILEAGE,VEHICLE_TYPE,SPEEDING_VIOLATIONS,DUIS,PAST_ACCIDENTS,OUTCOME,DEFAULT
0,569520,65+,female,majority,0-9y,high school,upper class,0.629027,1.0,after 2015,0.0,1.0,10238,12000.0,sedan,0,0,0,0.0,1
1,750365,16-25,male,majority,0-9y,none,poverty,0.357757,0.0,before 2015,0.0,0.0,10238,16000.0,sedan,0,0,0,1.0,0
2,199901,16-25,female,majority,0-9y,high school,working class,0.493146,1.0,before 2015,0.0,0.0,10238,11000.0,sedan,0,0,0,0.0,0
3,478866,16-25,male,majority,0-9y,university,working class,0.206013,1.0,before 2015,0.0,1.0,32765,11000.0,sedan,0,0,0,0.0,0
4,731664,26-39,male,majority,10-19y,none,working class,0.388366,1.0,before 2015,0.0,0.0,32765,12000.0,sedan,2,0,1,1.0,0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10000 non-null  int64
 1   AGE                  10000 non-null  object
 2   GENDER               10000 non-null  object
 3   RACE                 10000 non-null  object
 4   DRIVING_EXPERIENCE   10000 non-null  object
 5   EDUCATION            10000 non-null  object
 6   INCOME               10000 non-null  object
 7   CREDIT_SCORE         9018 non-null   float64
 8   VEHICLE_OWNERSHIP    10000 non-null  float64
 9   VEHICLE_YEAR         10000 non-null  object
 10  MARRIED              10000 non-null  float64
 11  CHILDREN             10000 non-null  float64
 12  POSTAL_CODE          10000 non-null  int64
 13  ANNUAL_MILEAGE       9043 non-null   float64
 14  VEHICLE_TYPE         10000 non-null  object
 15  SPEEDING_VIOLATIONS  10000 non-null  int64
 16  DUIS                 10000 non-null  int64
 17  PAST_ACCIDENTS       10000 non-null  int64
 18  OUTCOME              10000 non-null  float64
 19  DEFAULT              10000 non-null  int64
dtypes: float64(6), int64(6), object(8)
memory usage: 1.5+ MB

In [12]:
data = data[['GENDER', 'POSTAL_CODE', 'DEFAULT']]

In [13]:
data.head()

   GENDER  POSTAL_CODE  DEFAULT
0  female        10238        1
1    male        10238        0
2  female        10238        0
3    male        32765        0
4    male        32765        0

In [14]:
data.isna().sum()

GENDER         0
POSTAL_CODE    0
DEFAULT        0
dtype: int64

In [17]:
crosstab_gender = pd.crosstab(data['GENDER'], data['DEFAULT'], margins=True)
crosstab_gender

DEFAULT     0     1    All
GENDER
female   2324  2686   5010
male     2568  2422   4990
All      4892  5108  10000

In [18]:
proportion_by_gender = pd.crosstab(data['GENDER'], data['DEFAULT'], margins=True, normalize=True)
proportion_by_gender

DEFAULT       0       1    All
GENDER
female   0.2324  0.2686  0.501
male     0.2568  0.2422  0.499
All      0.4892  0.5108  1.000

In [37]:
crosstab_gender.iloc[0]

DEFAULT
0      2324
1      2686
All    5010
Name: female, dtype: int64